import React from "react";
import {
  FaDrumSteelpan,
  FaTemperatureHigh,
  FaLemon,
  FaBurn,
  FaAllergies,
  FaWater,
  FaOilCan,
  FaAtom,
  FaBacterium,
  FaThLarge,
  FaTh,
  FaVial,
  FaWaveSquare,
  FaGlassWhiskey,
  FaMendeley,
  FaPoll,
  FaFireAlt,
  FaBreadSlice,
  FaFlask,
  FaPencilAlt,
  FaClock,
} from "react-icons/fa";

export const positivo_negativo = [{ name: "positivo" }, { name: "negativo" }];

export const FORM_FIELDS = [
  {
    name: "hora_inicial",
    type: "time",
    icon: <FaClock size={12} />,
    required: true,
  },
  {
    name: "hora_final",
    type: "time",
    icon: <FaClock size={12} />,
    required: true,
  },
  {
    name: "silo",
    type: "text",
    icon: <FaDrumSteelpan size={12} />,
    required: true,
  },
  {
    name: "temperatura",
    type: "text",
    icon: <FaTemperatureHigh size={12} />,
    required: true,
    min: 0,
    max: 22,
  },
  {
    name: "acidez",
    type: "text",
    icon: <FaLemon size={12} />,
    required: true,
    step: "0.01",
    min: 0.13,
    max: 0.17,
  },
  {
    name: "ph",
    type: "text",
    icon: <FaAllergies size={12} />,
    required: true,
    min: 6.55,
    max: 6.75,
  },
  {
    name: "densidad",
    type: "text",
    icon: <FaWater size={12} />,
    required: true,
    min: 1.03,
    max: 1.033,
  },
  {
    name: "grasa",
    type: "text",
    icon: <FaOilCan size={12} />,
    required: true,
    min: 3,
    max: 1000,
  },
  {
    name: "proteina",
    type: "text",
    icon: <FaAtom size={12} />,
    required: true,
    min: 2.9,
    max: 1000,
  },
  {
    name: "crioscopia",
    type: "text",
    icon: <FaBacterium size={12} />,
    required: true,
    min: -0.53,
    max: -0.51,
  },
  {
    name: "solidos_no_grasos",
    type: "text",
    icon: <FaThLarge size={12} />,
    required: true,
    min: 8.3,
    max: 1000,
    readOnly: true,
  },
  {
    name: "solidos_totales",
    type: "text",
    icon: <FaTh size={12} />,
    required: true,
    min: 11.3,
    max: 1000,
    readOnly: true,
  },
  {
    name: "alcohol",
    type: "radio",
    icon: <FaBurn size={12} />,
    required: true,
  },
  {
    name: "antibiotico",
    type: "radio",
    icon: <FaVial size={12} />,
    required: true,
  },
  {
    name: "neutralizante",
    type: "radio",
    icon: <FaWaveSquare size={12} />,
    required: true,
  },
  {
    name: "cloruros",
    type: "radio",
    icon: <FaGlassWhiskey size={12} />,
    required: true,
  },
  {
    name: "peroxido",
    type: "radio",
    icon: <FaMendeley size={12} />,
    required: true,
  },
  {
    name: "peroxidasa",
    type: "radio",
    icon: <FaPoll size={12} />,
    required: true,
    def: "positivo",
  },
  {
    name: "fosfatasa",
    type: "radio",
    icon: <FaFireAlt size={12} />,
    required: true,
    def: "positivo",
  },
  {
    name: "almidon",
    type: "radio",
    icon: <FaBreadSlice size={12} />,
    required: true,
  },
  {
    name: "prueba_suero",
    type: "radio",
    icon: <FaFlask size={12} />,
    required: true,
  },
  {
    name: "observaciones",
    type: "textarea",
    icon: <FaPencilAlt size={12} />,
    required: false,
  },
];
